#!/bin/bash
#SBATCH --job-name=human_bismark
#SBATCH -A SBSANDME_LAB
#SBATCH -p standard
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=7
#SBATCH --mem-per-cpu=6G
#SBATCH --error=logs/bismark-%x.%j.err
#SBATCH --output=logs/bismark-%x.%j.out

module load bismark/0.23.1

bismark_genome_preparation /dfs9/ucightf-lab/projects/SmitQ/251103_1125Bio-13_SmitQ_BSseq/data/targeted_reference

